### ISSUE TITLE
Doesn't support Healthcheck

### ISSUE THREAD

**Issue by tochka** [cyberdelia/go-metrics-graphite#8]
I created Health Check metrics but I get a console notifications that unable to record
``` 2017/03/20 08:02:14 unable to record metric of type *metrics.StandardHealthcheck ```
You can find implementation for log output [there](https://github.com/rcrowley/go-metrics/blob/master/log.go#L33)

**Comment by zeim839** [comment]
@tochka A healthcheck returns a golang error type, which cannot be posted as a metric to graphite.
